const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/gabri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const XLSX = require('../vendor/xlsx.full.min.js');
const output = path.join(__dirname, 'results'); fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
  const checks = [], errors = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
  const pass = name => { checks.push(name); console.log('PASS', name); };
  const upload = text => page.locator('#file-input').setInputFiles({ name: 'colaboradores.csv', mimeType: 'text/csv', buffer: Buffer.from(text) });
  const collaborator = name => page.locator('#collaborator-options label').filter({ hasText: name }).locator('input');
  const company = name => page.locator('#company-options label').filter({ hasText: name }).locator('input');
  const count = async n => assert.equal(await page.locator('#result-count').textContent(), `Exibindo ${n} de 7 envios`);
  const csv = 'empresas;colaboradores;campanha;data de envio;enviados;entregues;lidos;cliques;canal\nEmpA;Colab1;Igual;2026-09-01;100;90;30;3;E-mail\nEmpA;Colab2;Igual;2026-09-01;200;180;90;9;E-mail\nEmpB;Colab1;Igual;2026-09-01;50;45;20;2;SMS\nEmpA;Colab3;Oferta;2026-09-02;300;270;90;9;WhatsApp\nEmpC;Colab4;Oferta;2026-09-02;400;360;180;18;E-mail\nEmpB;Colab5;Outra;2026-09-02;500;450;225;23;SMS\nEmpC;Colab6;Outra;2026-09-03;600;540;270;27;WhatsApp';
  const download = async (selector, filename) => { const pending = page.waitForEvent('download'); await page.locator(selector).first().click(); const file = path.join(output, filename); await (await pending).saveAs(file); return file; };
  try {
    await page.goto(pathToFileURL(path.join(__dirname, '..', 'index.html')).href);
    assert.deepEqual(await page.locator('#collaborator-options label').allTextContents(), ['Colab1', 'Colab2', 'Colab3', 'Colab4', 'Colab5', 'Colab6']);
    await page.locator('#performance-mode').selectOption('colaboradores');
    await page.locator('#listing-mode').selectOption('colaboradores');
    assert.equal(await page.locator('[data-collaborator-group]').count(), 6);
    assert.equal(await page.locator('#dispatch-metrics .metric-value').first().textContent(), '14');
    await page.screenshot({ path: path.join(output, 'colaboradores-demonstracao.png'), fullPage: true });
    pass('demonstração Colab1 a Colab6 e modo de produção/listagem por responsável');
    await upload(csv); await page.waitForFunction(() => document.querySelector('#result-count').textContent === 'Exibindo 7 de 7 envios');
    assert.equal(await page.locator('#dispatch-metrics .metric-value').first().textContent(), '7');
    assert.equal(await page.locator('#dispatch-metrics .metric-value').nth(1).textContent(), '6');
    assert.equal(await page.locator('#dispatch-metrics .metric-value').nth(2).textContent(), '3');
    assert.equal(await page.locator('[data-campaign-row]').count(), 7);
    const firstBar = page.locator('#engagement-chart .comparison-row').first();
    assert.equal(await firstBar.getAttribute('data-collaborator'), 'Colab1'); assert.match(await firstBar.textContent(), /2 disparos/);
    const daily = page.locator('#trend-chart g[data-collaborator="Colab1"][data-metric="registros"] circle');
    assert.match(await daily.getAttribute('aria-label'), /Disparos: 2$/); assert.equal(await page.locator('#trend-chart g[data-collaborator]').count(), 6);
    await daily.hover(); assert.match(await page.locator('#dashboard-tooltip').textContent(), /Empresas: EmpA, EmpB/);
    pass('produção: contagem de disparos, campanhas distintas, empresas e série diária por colaborador');
    await collaborator('Colab1').check(); await count(2);
    await collaborator('Colab2').check(); await count(3);
    await collaborator('Colab1').uncheck(); await count(1);
    await collaborator('Colab2').uncheck(); await count(7);
    pass('um/vários/nenhum colaborador: nenhuma seleção equivale a todos');
    await collaborator('Colab1').check(); await company('EmpB').check(); await count(1);
    await page.locator('#start-date').fill('2026-09-01'); await page.locator('#end-date').fill('2026-09-01'); await page.locator('[data-channel="SMS"]').click(); await page.locator('#campaign-search').fill('igual'); await count(1);
    for (const mode of ['empresas', 'campanhas', 'colaboradores']) { await page.locator('#performance-mode').selectOption(mode); await count(1); }
    for (const mode of ['empresas', 'campanhas', 'colaboradores']) { await page.locator('#listing-mode').selectOption(mode); await count(1); assert.equal(await page.locator('[data-campaign-row]').count(), 1); }
    await page.locator('[data-campaign-row]').hover(); assert.match(await page.locator('#dashboard-tooltip').textContent(), /Colaboradores: Colab1/);
    pass('empresa, responsável, busca, período e canal combinados nos três modos/listagens');
    const excelFile = await download('[data-action="excel"]', 'colaboradores-filtrados.xlsx');
    const book = XLSX.read(fs.readFileSync(excelFile), { type: 'buffer' });
    const raw = XLSX.utils.sheet_to_json(book.Sheets.Disparos), summary = XLSX.utils.sheet_to_json(book.Sheets.Resumo);
    assert.equal(raw.length, 1); assert.equal(raw[0].colaboradores, 'Colab1'); assert.equal(raw[0].empresas, 'EmpB');
    assert.equal(summary[0].Colaborador, 'Colab1'); assert.equal(summary[0].Disparos, 1); assert.equal(summary[0]['Empresas atendidas'], 1);
    const pdf = fs.readFileSync(await download('[data-action="pdf"]', 'colaboradores-filtrados.pdf'), 'latin1');
    assert.ok(pdf.startsWith('%PDF-')); assert.ok(pdf.includes('Colab1')); assert.ok(!pdf.includes('Colab2'));
    pass('Excel/PDF identificam responsável, produção e somente o recorte filtrado');
    await page.locator('#clear-filters').click(); await count(7);
    assert.equal(await page.locator('#collaborator-options input:checked').count(), 0);
    assert.equal(await page.locator('#performance-mode').inputValue(), 'colaboradores'); assert.equal(await page.locator('#listing-mode').inputValue(), 'colaboradores');
    const backup = JSON.parse(fs.readFileSync(await download('#backup-button', 'colaboradores-backup.json')));
    assert.equal(backup.version, 3); assert.equal(backup.rows.length, 7); assert.ok(backup.rows.every(row => row.colaborador));
    await page.reload(); await count(7); assert.match(await page.locator('#campaign-table-body').textContent(), /Colab6/);
    pass('limpeza mantém modos; backup v3 e persistência preservam responsáveis');
    const template = XLSX.read(fs.readFileSync(await download('[data-action="template"]', 'modelo-colaboradores.xlsx')), { type: 'buffer' });
    assert.equal(XLSX.utils.sheet_to_json(template.Sheets.Campanhas)[0].colaboradores, 'Colab1');
    await upload('empresas;colaboradores;campanha;enviados\nEmpA;Colab1;A;1\nEmpA;;B;2');
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('cancelada')); await count(7);
    pass('modelo inclui colaborador; responsável vazio rejeita importação inteira');
    await page.locator('#performance-mode').selectOption('colaboradores'); await page.locator('#listing-mode').selectOption('colaboradores');
    for (const width of [390, 768, 1440]) {
      await page.setViewportSize({ width, height: 1000 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true);
      if (width !== 768) await page.screenshot({ path: path.join(output, `colaboradores-${width}.png`), fullPage: true, style: '#toast{visibility:hidden}' });
    }
    await page.locator('#theme-button').click(); await page.screenshot({ path: path.join(output, 'colaboradores-escuro.png'), fullPage: true, style: '#toast{visibility:hidden}' });
    pass('produção e listagens responsivas em 390, 768 e 1440 px; tema escuro');
    await collaborator('Colab6').check(); await company('EmpA').check();
    assert.equal(await page.locator('#trend-chart svg').count(), 0); assert.equal(await page.locator('[data-collaborator-group]').count(), 0); assert.equal(await page.locator('[data-action="pdf"]').isDisabled(), true);
    await page.locator('#clear-filters').click();
    await page.locator('#restore-input').setInputFiles({ name: 'antigo.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...backup, version: 2, rows: backup.rows.map(({ colaborador, ...row }) => row) })) });
    await page.waitForFunction(() => document.querySelector('#campaign-table-body').textContent.includes('Colaborador não informado'));
    assert.equal(await page.locator('#legacy-collaborator-warning').isVisible(), true);
    await upload('empresas;campanha;enviados\nEmpA;Legada;10'); await page.waitForFunction(() => document.querySelector('#result-count').textContent === 'Exibindo 1 de 1 envios');
    assert.match(await page.locator('#toast').textContent(), /sem a coluna colaboradores/);
    pass('estado vazio; backup v2 e planilha antiga preservados sem atribuição falsa');
    assert.deepEqual(errors, []); pass('zero erros JavaScript');
    fs.writeFileSync(path.join(output, 'collaborators-report.json'), JSON.stringify({ date: new Date().toISOString(), checks, errors }, null, 2));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
