const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/gabri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const output = path.join(__dirname, 'results'); fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], checks = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
  const pass = name => { checks.push(name); console.log('PASS', name); };
  const box = page.locator('#dashboard-tooltip');
  const point = () => page.locator('#trend-chart g[data-company="EmpA"][data-metric="abertura"] circle').last();
  const insideViewport = async () => assert.equal(await box.evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.top >= 0 && r.right <= innerWidth && r.bottom <= innerHeight; }), true);
  try {
    await page.goto(pathToFileURL(path.join(__dirname, '..', 'index.html')).href);
    await point().hover(); assert.equal(await box.isVisible(), true);
    assert.match(await box.textContent(), /EmpA · 24\/09\/2026/);
    assert.match(await box.textContent(), /Aberturas: 5\.926/); assert.match(await box.textContent(), /Cliques: 1\.864/);
    assert.match(await box.textContent(), /Entregues: 14\.846/);
    assert.equal(await point().getAttribute('aria-describedby'), 'dashboard-tooltip'); await insideViewport();
    await page.screenshot({ path: path.join(output, 'tooltip-grafico-claro.png') });
    pass('ponto temporal: caixa com empresa, data, somas e taxas do dia');
    await page.mouse.move(1, 1); assert.equal(await box.isVisible(), false);
    await point().focus(); assert.equal(await box.isVisible(), true);
    await page.keyboard.press('Escape'); assert.equal(await box.isVisible(), false);
    assert.equal(await point().getAttribute('aria-describedby'), null);
    await page.keyboard.press('Tab'); assert.equal(await box.isVisible(), true);
    pass('saída do mouse, foco por teclado, descrição acessível e Escape');
    await page.locator('#campaign-search').fill('Carrinho'); assert.equal(await box.isVisible(), false);
    await point().hover(); assert.match(await box.textContent(), /Aberturas: 1\.065/); assert.match(await box.textContent(), /Cliques: 432/);
    await page.locator('#clear-filters').click(); assert.equal(await box.isVisible(), false);
    pass('caixa respeita filtro e fecha ao atualizar os dados');
    await page.locator('#dispatch-metrics .metric-card').first().hover();
    assert.match(await box.textContent(), /Total de envios/); assert.match(await box.textContent(), /88\.480/);
    await page.locator('#engagement-chart .comparison-row').first().hover();
    assert.match(await box.textContent(), /Canal:/); assert.match(await box.textContent(), /CTR/);
    await page.locator('[data-company-group]').first().hover(); assert.match(await box.textContent(), /disparos/);
    await page.locator('[data-campaign-row]').first().hover(); assert.match(await box.textContent(), /Opt-out:/);
    await page.locator('#listing-mode').selectOption('campanhas'); await page.locator('[data-campaign-row]').first().hover();
    assert.match(await box.textContent(), /Aberturas:/);
    pass('indicadores, comparativo e ambas as listagens exibem detalhes');
    await page.locator('#theme-button').click(); await point().hover();
    assert.equal(await box.isVisible(), true); await insideViewport();
    assert.equal(await box.evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(23, 35, 49)');
    await page.screenshot({ path: path.join(output, 'tooltip-grafico-escuro.png') });
    await page.setViewportSize({ width: 390, height: 900 }); assert.equal(await box.isVisible(), false);
    await point().focus(); assert.equal(await box.isVisible(), true); await insideViewport();
    await page.screenshot({ path: path.join(output, 'tooltip-mobile.png') });
    pass('tema escuro e caixa dentro dos limites da tela em desktop/celular');
    await page.locator('[data-page="pos-evento"]').click(); assert.equal(await box.isVisible(), false);
    await page.locator('#event-metrics .metric-card').first().hover(); assert.equal(await box.isVisible(), true);
    await page.locator('#event-search').fill('teste'); assert.equal(await box.isVisible(), false);
    pass('navegação e atualização de eventos removem detalhes antigos');
    await page.locator('[data-page="disparos"]').click();
    await page.locator('#restore-input').setInputFiles({ name: 'texto.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ version: 2, source: 'imported', events: [], rows: [{ empresa: '<img src=x onerror="window.injected=1">', campanha: 'Texto <b>literal</b>', date: '2026-09-24', enviados: 100, entregues: 90, lidos: 30, cliques: 3, canal: 'E-mail' }] })) });
    await page.waitForFunction(() => document.querySelector('#campaign-table-body').textContent.includes('Texto <b>literal</b>'));
    await page.locator('[data-campaign-row]').first().hover(); assert.match(await box.textContent(), /Texto <b>literal<\/b>/);
    assert.equal(await box.locator('img, b').count(), 0); assert.equal(await page.evaluate(() => window.injected), undefined);
    assert.deepEqual(errors, []); pass('conteúdo importado permanece texto seguro; zero erros JavaScript');
    fs.writeFileSync(path.join(output, 'tooltips-report.json'), JSON.stringify({ date: new Date().toISOString(), checks, errors }, null, 2));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
